### ISSUE TITLE
After installing md-steppers, get fonts errored message when I run gulp serve

### ISSUE THREAD

**Issue by jinisha** [roelbarreto/md-steppers#1]
After installing md-steppers, get fonts errored message when  I run gulp serve. I am running this on Windows 7.

Please advise!

**Comment by roelbarreto** [comment]
I'll investigate

**Comment by roelbarreto** [comment]
@jinisha I updated the package.json main file can you check on your end? Thanks
https://github.com/ipiz/md-steppers/releases/tag/0.2.1

**Comment by jinisha** [comment]
Thanks for making the changes but I am still seeing the same issue
![image](https://cloud.githubusercontent.com/assets/9576963/14045247/e88281de-f26e-11e5-832b-2e95a811a651.png)

**Comment by roelbarreto** [comment]
@jinisha I also update the bower main files. Can you update your md-steppers version to 0.2.2?
Please let me know when the problem still exist.
Thanks.

**Comment by jinisha** [comment]
Thanks! That fixed the issue.
