### ISSUE TITLE
md-stepper header not displaying properly

### ISSUE THREAD

**Issue by jadjoubran** [roelbarreto/md-steppers#8]
Hello,

First thank you so much for this package :smile: 

I've installed this into an angular material app and added the basic demo you have in the `readme.md` but the header looks wrong.. I have verified that the CSS is being loaded properly

![header preview](http://i.imgur.com/xXMk4xp.png)

Any idea?

**Comment by roelbarreto** [comment]
@jadjoubran Can you check this fiddle https://jsfiddle.net/ipiz/vcdbuyru/
or you can check this for more advance example https://jsfiddle.net/ipiz/vcdbuyru/1/
I verified this as bug. If you put long content inside the steppers it suddenly destroy the ui.

**Comment by jadjoubran** [comment]
@ipiz Thanks for the fiddles! I'll use them to get started

**Comment by roelbarreto** [comment]
@jadjoubran i released 0.2.3 for the bug fix and your issue should fix now, you can check it here https://jsfiddle.net/ipiz/vcdbuyru/2/
You can use `md-stretch-steppers="always"` to make your steps always stretched.
Hope this help.
Thanks

**Comment by jadjoubran** [comment]
@ipiz thank you! But unfortunately I still have an issue
![screenshot](http://i.imgur.com/KAog0Km.png)
Are you sure the fiddle is using the latest version?

**Comment by stunaz** [comment]
@jadjoubran perhaps it will be best if you can isolate your code on jsfiddle or codepen. we dont even know if it is your own css which breaks things

**Comment by jadjoubran** [comment]
@stunaz you're right.. It works [here](http://codepen.io/anon/pen/ONjWpa?editors=1000) with the latest version from rawgit
Thanks!
